# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.COX <- function(tps, cureE, gene, delta) {
    .Call(`_iBST_COX`, tps, cureE, gene, delta)
}

rcpp_hello_world <- function() {
    .Call(`_iBST_rcpp_hello_world`)
}

